export const EVENTS_CLEAR = 'EVENTS_CLEAR';
export const EVENTS_DELETE = 'EVENTS_DELETE';
export const EVENTS_FILTER = 'EVENTS_FILTER';
export const EVENTS_FORM_DATA = 'EVENTS_FORM_DATA';
export const EVENTS_ADD = 'EVENTS_ADD';
export const EVENT_GET_START = 'EVENT_GET_START';
export const EVENT_GET_SUCCESS = 'EVENT_GET_SUCCESS';
export const EVENT_GET_ERROR = 'EVENT_GET_ERROR';


export const DETAILS_FIND = 'DETAILS_FIND';
export const DETAILS_GET_START = 'DETAILS_GET_START';
export const DETAILS_GET_SUCCESS = 'DETAILS_GET_SUCCESS';
export const DETAILS_GET_ERROR = 'DETAILS_GET_ERROR';
