// Events actions
export const EVENTS_FILTER = 'EVENTS_FILTER';
export const EVENTS_GET_START = 'EVENTS_GET_START';
export const EVENTS_GET_SUCCESS = 'EVENTS_GET_SUCCESS';
export const EVENTS_GET_ERROR = 'EVENTS_GET_ERROR';

export const DETAILS_GET_START = 'DETAILS_GET_START';
export const DETAILS_GET_SUCCESS = 'DETAILS_GET_SUCCESS';
export const DETAILS_GET_ERROR = 'DETAILS_GET_ERROR';


export const TYPE_GET_START = 'TYPE_GET_START';
export const TYPE_GET_SUCCESS = 'TYPE_GET_SUCCESS';
export const TYPE_GET_ERROR = 'TYPE_GET_ERROR';
